/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GiveawaysRouteImport } from './routes/giveaways'
import { Route as Googlece89cc86aa7767ddDothtmlRouteImport } from './routes/googlece89cc86aa7767dd[.]html'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MonthlyRouteImport } from './routes/monthly'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrizesRouteImport } from './routes/prizes'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SpinRouteImport } from './routes/spin'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WeeklyRouteImport } from './routes/weekly'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesHowToGetTrafficToANewWebsiteRouteImport } from './routes/guides.how-to-get-traffic-to-a-new-website'
import { Route as PayIndexRouteImport } from './routes/pay.index'
import { Route as PayCancelRouteImport } from './routes/pay.cancel'
import { Route as PaySuccessRouteImport } from './routes/pay.success'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveawaysRoute = GiveawaysRouteImport.update({
  id: '/giveaways',
  path: '/giveaways',
  getParentRoute: () => rootRouteImport,
} as any)
const Googlece89cc86aa7767ddDothtmlRoute =
  Googlece89cc86aa7767ddDothtmlRouteImport.update({
    id: '/googlece89cc86aa7767dd.html',
    path: '/googlece89cc86aa7767dd.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyRoute = MonthlyRouteImport.update({
  id: '/monthly',
  path: '/monthly',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrizesRoute = PrizesRouteImport.update({
  id: '/prizes',
  path: '/prizes',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SpinRoute = SpinRouteImport.update({
  id: '/spin',
  path: '/spin',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeklyRoute = WeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesHowToGetTrafficToANewWebsiteRoute =
  GuidesHowToGetTrafficToANewWebsiteRouteImport.update({
    id: '/guides/how-to-get-traffic-to-a-new-website',
    path: '/guides/how-to-get-traffic-to-a-new-website',
    getParentRoute: () => rootRouteImport,
  } as any)
const PayIndexRoute = PayIndexRouteImport.update({
  id: '/pay/',
  path: '/pay/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayCancelRoute = PayCancelRouteImport.update({
  id: '/pay/cancel',
  path: '/pay/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const PaySuccessRoute = PaySuccessRouteImport.update({
  id: '/pay/success',
  path: '/pay/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/giveaways': typeof GiveawaysRoute
  '/googlece89cc86aa7767dd.html': typeof Googlece89cc86aa7767ddDothtmlRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/monthly': typeof MonthlyRoute
  '/privacy': typeof PrivacyRoute
  '/prizes': typeof PrizesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rules': typeof RulesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spin': typeof SpinRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/weekly': typeof WeeklyRoute
  '/guides/how-to-get-traffic-to-a-new-website': typeof GuidesHowToGetTrafficToANewWebsiteRoute
  '/pay/cancel': typeof PayCancelRoute
  '/pay/success': typeof PaySuccessRoute
  '/guides/': typeof GuidesIndexRoute
  '/pay/': typeof PayIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/giveaways': typeof GiveawaysRoute
  '/googlece89cc86aa7767dd.html': typeof Googlece89cc86aa7767ddDothtmlRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/monthly': typeof MonthlyRoute
  '/privacy': typeof PrivacyRoute
  '/prizes': typeof PrizesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rules': typeof RulesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spin': typeof SpinRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/weekly': typeof WeeklyRoute
  '/guides/how-to-get-traffic-to-a-new-website': typeof GuidesHowToGetTrafficToANewWebsiteRoute
  '/pay/cancel': typeof PayCancelRoute
  '/pay/success': typeof PaySuccessRoute
  '/guides': typeof GuidesIndexRoute
  '/pay': typeof PayIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/giveaways': typeof GiveawaysRoute
  '/googlece89cc86aa7767dd.html': typeof Googlece89cc86aa7767ddDothtmlRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/monthly': typeof MonthlyRoute
  '/privacy': typeof PrivacyRoute
  '/prizes': typeof PrizesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rules': typeof RulesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/spin': typeof SpinRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/weekly': typeof WeeklyRoute
  '/guides/how-to-get-traffic-to-a-new-website': typeof GuidesHowToGetTrafficToANewWebsiteRoute
  '/pay/cancel': typeof PayCancelRoute
  '/pay/success': typeof PaySuccessRoute
  '/guides/': typeof GuidesIndexRoute
  '/pay/': typeof PayIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/archive'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/giveaways'
    | '/googlece89cc86aa7767dd.html'
    | '/how-it-works'
    | '/login'
    | '/monthly'
    | '/privacy'
    | '/prizes'
    | '/robots.txt'
    | '/rules'
    | '/sitemap.xml'
    | '/spin'
    | '/terms'
    | '/wallet'
    | '/weekly'
    | '/guides/how-to-get-traffic-to-a-new-website'
    | '/pay/cancel'
    | '/pay/success'
    | '/guides/'
    | '/pay/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/archive'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/giveaways'
    | '/googlece89cc86aa7767dd.html'
    | '/how-it-works'
    | '/login'
    | '/monthly'
    | '/privacy'
    | '/prizes'
    | '/robots.txt'
    | '/rules'
    | '/sitemap.xml'
    | '/spin'
    | '/terms'
    | '/wallet'
    | '/weekly'
    | '/guides/how-to-get-traffic-to-a-new-website'
    | '/pay/cancel'
    | '/pay/success'
    | '/guides'
    | '/pay'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/archive'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/giveaways'
    | '/googlece89cc86aa7767dd.html'
    | '/how-it-works'
    | '/login'
    | '/monthly'
    | '/privacy'
    | '/prizes'
    | '/robots.txt'
    | '/rules'
    | '/sitemap.xml'
    | '/spin'
    | '/terms'
    | '/wallet'
    | '/weekly'
    | '/guides/how-to-get-traffic-to-a-new-website'
    | '/pay/cancel'
    | '/pay/success'
    | '/guides/'
    | '/pay/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArchiveRoute: typeof ArchiveRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  GiveawaysRoute: typeof GiveawaysRoute
  Googlece89cc86aa7767ddDothtmlRoute: typeof Googlece89cc86aa7767ddDothtmlRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  MonthlyRoute: typeof MonthlyRoute
  PrivacyRoute: typeof PrivacyRoute
  PrizesRoute: typeof PrizesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RulesRoute: typeof RulesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpinRoute: typeof SpinRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRoute
  WeeklyRoute: typeof WeeklyRoute
  GuidesHowToGetTrafficToANewWebsiteRoute: typeof GuidesHowToGetTrafficToANewWebsiteRoute
  PayCancelRoute: typeof PayCancelRoute
  PaySuccessRoute: typeof PaySuccessRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  PayIndexRoute: typeof PayIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giveaways': {
      id: '/giveaways'
      path: '/giveaways'
      fullPath: '/giveaways'
      preLoaderRoute: typeof GiveawaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/googlece89cc86aa7767dd.html': {
      id: '/googlece89cc86aa7767dd.html'
      path: '/googlece89cc86aa7767dd.html'
      fullPath: '/googlece89cc86aa7767dd.html'
      preLoaderRoute: typeof Googlece89cc86aa7767ddDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly': {
      id: '/monthly'
      path: '/monthly'
      fullPath: '/monthly'
      preLoaderRoute: typeof MonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prizes': {
      id: '/prizes'
      path: '/prizes'
      fullPath: '/prizes'
      preLoaderRoute: typeof PrizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spin': {
      id: '/spin'
      path: '/spin'
      fullPath: '/spin'
      preLoaderRoute: typeof SpinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekly': {
      id: '/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof WeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/how-to-get-traffic-to-a-new-website': {
      id: '/guides/how-to-get-traffic-to-a-new-website'
      path: '/guides/how-to-get-traffic-to-a-new-website'
      fullPath: '/guides/how-to-get-traffic-to-a-new-website'
      preLoaderRoute: typeof GuidesHowToGetTrafficToANewWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/': {
      id: '/pay/'
      path: '/pay'
      fullPath: '/pay/'
      preLoaderRoute: typeof PayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/cancel': {
      id: '/pay/cancel'
      path: '/pay/cancel'
      fullPath: '/pay/cancel'
      preLoaderRoute: typeof PayCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/success': {
      id: '/pay/success'
      path: '/pay/success'
      fullPath: '/pay/success'
      preLoaderRoute: typeof PaySuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArchiveRoute: ArchiveRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  GiveawaysRoute: GiveawaysRoute,
  Googlece89cc86aa7767ddDothtmlRoute: Googlece89cc86aa7767ddDothtmlRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  MonthlyRoute: MonthlyRoute,
  PrivacyRoute: PrivacyRoute,
  PrizesRoute: PrizesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RulesRoute: RulesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpinRoute: SpinRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRoute,
  WeeklyRoute: WeeklyRoute,
  GuidesHowToGetTrafficToANewWebsiteRoute:
    GuidesHowToGetTrafficToANewWebsiteRoute,
  PayCancelRoute: PayCancelRoute,
  PaySuccessRoute: PaySuccessRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  PayIndexRoute: PayIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
